// <auto-generated />
using System;
using InvestmentsServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvestmentsServer.Migrations
{
    [DbContext(typeof(InvestmentDbContext))]
    [Migration("20260126183039_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("InvestmentsServer.Models.ActiveInvestment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExpectedReturn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EndTime");

                    b.HasIndex("Username");

                    b.ToTable("ActiveInvestments");
                });

            modelBuilder.Entity("InvestmentsServer.Models.UserAccount", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InvestmentsServer.Models.ActiveInvestment", b =>
                {
                    b.HasOne("InvestmentsServer.Models.UserAccount", null)
                        .WithMany("ActiveInvestments")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InvestmentsServer.Models.UserAccount", b =>
                {
                    b.Navigation("ActiveInvestments");
                });
#pragma warning restore 612, 618
        }
    }
}
